# Generated by Django 3.0 on 2020-01-07 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0002_auto_20200107_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutomers', to=settings.AUTH_USER_MODEL),
        ),
    ]
