# Generated by Django 3.0 on 2019-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20191213_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_options', models.CharField(choices=[('savings', 'SAVINGS'), ('checkings', 'CHECKINGS'), ('business', 'BUSINESS')], default=('savings', 'SAVINGS'), max_length=20)),
                ('account_type', models.CharField(choices=[('business', 'BUSINESS'), ('personal', 'PERSONAL'), ('charity', 'CHARITY')], default=('business', 'BUSINESS'), max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_options',
        ),
    ]
