# Generated by Django 3.0 on 2020-01-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200107_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
