# Generated by Django 3.0.2 on 2020-01-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200108_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
