# Generated by Django 3.0.2 on 2020-01-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200110_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='bank.Branch'),
        ),
    ]
