# Generated by Django 3.0 on 2019-12-13 22:24

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_options', models.CharField(choices=[('savings', 'SAVINGS'), ('checkings', 'CHECKINGS'), ('business', 'BUSINESS')], default=('savings', 'SAVINGS'), max_length=20)),
                ('account_type', models.CharField(choices=[('business', 'BUSINESS'), ('personal', 'PERSONAL'), ('charity', 'CHARITY')], default=('business', 'BUSINESS'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=('male', 'MALE'), max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=10)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite', models.DecimalField(decimal_places=1, max_digits=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
            ],
        ),
    ]
