# Generated by Django 3.0.2 on 2020-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200124_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='user',
            new_name='users',
        ),
    ]
